services:
  - type: web
    name: klemdesk
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: NODE_ENV=production npm run start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
