services:
  - type: web
    name: robice
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: NODE_ENV=production npm run start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
